language: python
python:
- 3.6
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
- openssl aes-256-cbc -K $encrypted_f60140f9fdb6_key -iv $encrypted_f60140f9fdb6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- sudo apt-get install binutils libproj-dev gdal-bin spatialite-bin
install:
- sudo apt-get install -y postgresql-9.6-postgis-2.3
- sudo service postgresql restart
- pip install -r .requirements/dev.txt
before_script:
  - psql -U postgres -c "CREATE USER song WITH SUPERUSER PASSWORD 'dnflwlq';"
  - psql -U postgres -c "CREATE DATABASE \"fc-project\" WITH OWNER=song LC_COLLATE='C' TEMPLATE template0;"
  - psql -U postgres -d fc-project -c "CREATE EXTENSION postgis;"
script:
- "./app/manage.py test --settings=config.settings.dev"