language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_f60140f9fdb6_key -iv $encrypted_f60140f9fdb6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- sudo apt-get install binutils libproj-dev gdal-bin spatialite-bin
install:
- pip install -r .requirements/dev.txt
script:
- "./app/manage.py test"